### PR TITLE
Migrate to GitHub Actions from Travis

### PR DESCRIPTION
**Pull request by sideeffffect**
I don't have any experience with multi-Scala-version GHA and Gradle, but this is what I've come up with.
I'll probably also need privileges to set up the secrets.

In the long term, sbt (and perhaps even something like https://github.com/djspiewak/sbt-github-actions) is something to consider. But for now, this should do.

### CODE REVIEW

**Comment by augi** [comment]
I've just assigned you the Admin role.

**Comment by sideeffffect** [comment]
I would need to move the `BINTRAY_KEY` and `BINTRAY_USER` variables from Travis to GitHub itself, but Travis won't reveal their content. Do we have them saved somewhere?
If not, could somebody please add me the necessary privileges in Bintray to see these or create new ones (the key, presumably).

**Comment by augi** [comment]
I can add you to our Bitray organization but I have to know your username there.

**Comment by sideeffffect** [comment]
https://bintray.com/sideeffffect

**Comment by augi** [comment]
You should receive an invitation.

**Comment by sideeffffect** [comment]
@jendakol would you like to "test" releasing a new version of this library, just to see if it works?
Or would you rather wait for more features to be added before a normal release?

**Pull request merged**
