### PR TITLE
Allow to set the max channels parameter

### PR DESCRIPTION
**Pull request by tzimisce012**
https://github.com/avast/rabbitmq-scala-client/issues/57

### CODE REVIEW

**Review by augi — APPROVED** [review]

**Review by jendakol — COMMENTED** [review]
It looks pretty simple and there's nothing much to add, however, one question came to my mind anyway: what will happen when the limit is reached? Did you test if the underlying client throws an exception or how that behaves?

**Comment by tzimisce012** [comment]
There is already a limit on the client of 2048 channels, which i left by default. When the limit is reached, the client throws an exception. This is a behaviour expected by the users that modify the amount of channels. You can check this values on `com.rabbitmq.client.ConnectionFactory`, the static value `DEFAULT_CHANNEL_MAX`

**Comment by jendakol** [comment]
@tzimisce012 Would you mind writing a simple test to `LiveTest.scala` where the exception would be expected?

**Comment by tzimisce012** [comment]
Sorry guys, I was on vacation but I am coming back to work on this week. I will add the test 👍

**Comment by jendakol** [comment]
@tzimisce012 Hi, any progress? 😉

**Comment by jendakol** [comment]
@tzimisce012 Hi, is there any chance you get back to this?

**Comment by jendakol** [comment]
Will do it by myself.

**Pull request closed without merging**
