### PR TITLE
chore: Update PureConfig and some other dependencies

### PR DESCRIPTION
**Pull request by jakubjanecek**

### CODE REVIEW

**Review by jendakol — APPROVED** [review]
I believe you're aware of the pureconfig incompatibility, still feel a need to mention it explicitly :-) Make it 8.3 then.

**Review by augi — APPROVED** [review]

**Comment by jendakol** [comment]
Squash and merge it is!

**Comment by sideeffffect** [comment]
:tada: btw shouldn't we introduce Scala Steward and Mergify to the `rabbitmq-scala-client` project? @jendakol would you like me to do it?

**Comment by jakubjanecek** [comment]
This project is using Gradle so Scala Steward won't work for this repo.

**Pull request merged**
